import { CharacterConstants, CharacterProfile, GearBonus } from "./types";

export const charConstantData: Record<string, CharacterConstants> = {
  camellya: {
    id: "camellya",
    name: "Camellya",
    weaponType: "Sword",
    weapon: "Red Spring",
    echo: "Crownless (NM)",
    baseHp: 826,
    baseAtk: 36,
    baseDef: 95,
    MinorForte1: "Attack",
    MinorForte2: "Crit Dmg",
    image: "https://i.imgur.com/CpnmtcA.png",
    element: "Havoc",
    maxForte: 100,
    maxForte2: 0,
  },
  encore: {
    id: "encore",
    name: "Encore",
    weaponType: "Rectifier",
    weapon: "Stringmaster",
    echo: "Inferno Rider",
    baseHp: 841,
    baseAtk: 34,
    baseDef: 102,
    MinorForte1: "Attack",
    MinorForte2: "Fusion",
    image: "https://i.imgur.com/KUz0Psh.png",
    element: "Fusion",
    maxForte: 100,
    maxForte2: 0,
  },
  sanhua: {
    id: "sanhua",
    name: "Sanhua",
    weaponType: "Sword",
    weapon: "Emerald of Genesis",
    echo: "Impermanence Heron",
    baseHp: 805,
    baseAtk: 22,
    baseDef: 77,
    MinorForte1: "Attack",
    MinorForte2: "Glacio",
    image: "https://i.imgur.com/jpoAsFp.png",
    element: "Glacio",
    maxForte: 100,
    maxForte2: 0,
  },
  shorekeeper: {
    id: "shorekeeper",
    name: "Shorekeeper",
    weaponType: "Rectifier",
    weapon: "Stellar Symphony",
    echo: "Fallacy of No Return",
    baseHp: 1337,
    baseAtk: 23,
    baseDef: 90,
    MinorForte1: "Health",
    MinorForte2: "Healing",
    image: "https://i.imgur.com/iaR9PpA.png",
    element: "Spectro",
    maxForte: 5,
    maxForte2: 0,
  },
};
export const bonusSchema: GearBonus = {
  hp: 0,
  hpFlat: 0,
  atk: 0,
  atkFlat: 0,
  def: 0,
  defFlat: 0,
  critRate: 0,
  critDamage: 0,
  energyRegen: 0,
  basicBonus: 0,
  skillBonus: 0,
  heavyBonus: 0,
  liberationBonus: 0,
  elementBonus: 0,
};

export const charInputData: CharacterProfile = {
  name: "string",
  image: "/favicon.ico",
  sequence: "string",
  weapon: "string",
  weaponRank: 0,
  echo: "string",
  bonus: {
  hp: 0,
  hpFlat: 0,
  atk: 0,
  atkFlat: 0,
  def: 0,
  defFlat: 0,
  critRate: 0,
  critDamage: 0,
  energyRegen: 0,
  basicBonus: 0,
  skillBonus: 0,
  heavyBonus: 0,
  liberationBonus: 0,
  elementBonus: 0,
  },
};

export const charStatData: CharacterProfile = {
  name: "string",
  image: "/favicon.ico",
  sequence: "string",
  weapon: "string",
  weaponRank: 0,
  echo: "string",
  bonus: {
  hp: 0,
  hpFlat: 0,
  atk: 0,
  atkFlat: 0,
  def: 0,
  defFlat: 0,
  critRate: 0,
  critDamage: 0,
  energyRegen: 0,
  basicBonus: 0,
  skillBonus: 0,
  heavyBonus: 0,
  liberationBonus: 0,
  elementBonus: 0,
  },
};
